define(['link'], function(Link) {
    var Module = function() {
    };

    Module.prototype.routes = [
        Link.route('respond', { uri:"^/?$" }),
        Link.route('links', { uri:"^/?$" })
    ];

    Module.prototype.respond = function(request) {
        if (/json/.test(request.accept)) {
            var obj = { a:'1', b:'2', c:'3' };
            return Link.response(200, obj, 'application/json');
        }
        if (/html/.test(request.accept)) {
            return Link.response(200, '<h1>Test Response!!</h1><h3>(generated by a server in the browser)</h3>', 'text/html');
        }
        return Link.response(200, 'ok', 'text/plain');
    };

    Module.prototype.links = function(request, match, response) {
        response.link = [{ uri:'#', rel:'test' }];
        return response;
    };

    return Module;
});
