define(['link', 'lib/html+json'], function(Link, HtmlJson) {
    var Server = function() {
    };

    Server.prototype.routes = [
        Link.route('respond', { uri:"^/?$" }),
        Link.route('links', { uri:"^/?$" })
    ];

    Server.prototype.respond = function(request) {
        if (/html\+json/.test(request.accept)) {
            var node = HtmlJson.mknode(0,0,0,['<h1>Test Html+Json Response</h1>','<h3>(generated by a server in the browser)</h3>']);
            HtmlJson.addScript(node,'onrender',function(x,y) { console.log(x, y, this); },'context','arg');
            return Link.response(200, node, 'application/html+json');
        }
        if (/json/.test(request.accept)) {
            var obj = { a:'1', b:'2', c:'3' };
            return Link.response(200, obj, 'application/json');
        }
        if (/html/.test(request.accept)) {
            return Link.response(200, '<h1>Test Response!!</h1><h3>(generated by a server in the browser)</h3>', 'text/html');
        }
        return Link.response(200, 'ok', 'text/plain');
    };

    Server.prototype.links = function(request, match, response) {
        response.link = [{ uri:'#', rel:'test' }];
        return response;
    };

    return Server;
});
